<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mzn</string>
		<string>dzn</string>
	</array>
	<key>name</key>
	<string>MiniZinc (MZN)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\%.*</string>
			<key>name</key>
			<string>comment.line.percentage.mzn</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.*?\'</string>
			<key>name</key>
			<string>string.quoted.single.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\".*?\"</string>
			<key>name</key>
			<string>string.quoted.double.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ann|annotation|any|constraint|function|in|include|list|of|op|output|minimize|maximize|par|predicate|record|satisfy|solve|test|type|var)\b</string>
			<key>name</key>
			<string>keyword.control.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(array|set|bool|enum|float|int|string|tuple)\b</string>
			<key>name</key>
			<string>storage.type.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|forall|if|then|else|endif|where)\b</string>
			<key>name</key>
			<string>keyword.control.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abort|abs|acosh|array_intersect|array_union|array1d|array2d|array3d|array4d|array5d|array6d|asin|assert|atan|bool2int|card|ceil|concat|cos|cosh|dom|dom_array|dom_size|fix|exp|floor|index_set|index_set_1of2|index_set_2of2|index_set_1of3|index_set_2of3|index_set_3of3|int2float|is_fixed|join|lb|lb_array|length|ln|log|log2|log10|min|max|pow|product|round|set2array|show|show_int|show_float|sin|sinh|sqrt|sum|tan|tanh|trace|ub|ub_array)\b</string>
			<key>name</key>
			<string>entity.name.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(circuit|disjoint|maximum|maximum_arg|member|minimum|minimum_arg|network_flow|network_flow_cost|partition_set|range|roots|sliding_sum|subcircuit|sum_pred)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(alldifferent|all_different|all_disjoint|all_equal|alldifferent_except_0|nvalue|symmetric_all_different)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(lex2|lex_greater|lex_greatereq|lex_less|lex_lesseq|strict_lex2|value_precede|value_precede_chain)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(arg_sort|decreasing|increasing|sort)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int_set_channel|inverse|inverse_set|link_set_to_booleans)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(among|at_least|at_most|at_most1|count|count_eq|count_geq|count_gt|count_leq|count_lt|count_neq|distribute|exactly|global_cardinality|global_cardinality_closed|global_cardinality_low_up|global_cardinality_low_up_closed)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bin_packing|bin_packing_capa|bin_packing_load|diffn|diffn_k|diffn_nonstrict|diffn_nonstrict_k|geost|geost_bb|geost_smallest_bb|knapsack)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(alternative|cumulative|disjunctive|disjunctive_strict|span)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(regular|regular_nfa|table)\b</string>
			<key>name</key>
			<string>support.function.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(not|\+|-)\b</string>
			<key>name</key>
			<string>keyword.operator.math.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&lt;-&gt;|-&gt;|&lt;-|\\/|xor|/\\)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&lt;|&gt;|&lt;=|&gt;=|==|=|!=)\b</string>
			<key>name</key>
			<string>keyword.operator.math.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\+|-|\*|/|div|mod)\b</string>
			<key>name</key>
			<string>keyword.operator.math.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in|subset|superset|union|diff|symdiff|intersect)\b</string>
			<key>name</key>
			<string>keyword.operator.sets.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|\.\.|\+\+</string>
			<key>name</key>
			<string>keyword.operator.math.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([_A-Za-z])(\w*)\b</string>
			<key>name</key>
			<string>variable.other.mzn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+-]?)\d+(\.[^\.]\d*)?([eE][-+]?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.mzn</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mzn</string>
	<key>uuid</key>
	<string>5927bf82-cf44-455a-bd58-fed8cc0d02cc</string>
</dict>
</plist>
